### ISSUE TITLE
Add an examples/ directory in root with next.js and node.js examples

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/auto-sdk#24]
## Add an examples/ directory in root with next.js and node.js examples

```[tasklist]
### Tasks
- [x] Create an example/ directory in the root directory with node and next children directory
- [ ] https://github.com/subspace/auto-sdk/issues/30
- [ ] https://github.com/subspace/auto-sdk/issues/31
```
